# 2015-11-07 토요일 R기초 이상열  
## R맛보기 및 코드설명

### 1) R맛보기

In [19]:
x <- 2*3

In [20]:
x

[1] 6

In [21]:
myvector <- c(8,6,9,10,5)

In [22]:
myvector

[1]  8  6  9 10  5

In [23]:
myvector[4]

[1] 10

In [24]:
mylist <- list(name="Fred", wife="Mary", myvector)

In [25]:
mylist

$name
[1] "Fred"

$wife
[1] "Mary"

[[3]]
[1]  8  6  9 10  5

In [30]:
mynames <- c("mary", "john", "ahn", "sinead", "joe", "mary", "jim", "john", "simon")

In [31]:
table(mynames)

mynames
   ahn    jim    joe   john   mary  simon sinead 
     1      1      1      2      2      1      1 

In [32]:
mytable <- table(mynames)

In [33]:
mytable[[4]]

[1] 2

In [34]:
log10(100)

[1] 2

In [35]:
mean(myvector)

[1] 7.6

In [36]:
myfunction <- function(x) {
    return(20 + (x*x))
}

In [38]:
myfunction(10)

[1] 120

In [39]:
myfunction(25)

[1] 645

In [40]:
myFamilyNames <- c("Dad", "Mom", "Sis", "Bro", "Dog")

In [41]:
myFamilyNames

[1] "Dad" "Mom" "Sis" "Bro" "Dog"

In [42]:
myFamilyAges <- c(43,42,12,8,5)

In [43]:
myFamilyAges

[1] 43 42 12  8  5

In [44]:
myFamilyGenders <- c("Male", "Female", "Female", "Male", "Female")

In [46]:
myFamilyWeights <- c(188,136,83,61,44)

In [55]:
myFamily <- data.frame(myFamilyNames, myFamilyAges, myFamilyGenders, myFamilyWeights)

In [48]:
myFamily

myFamilyNames myFamilyAges myFamilyGenders myFamilyWeights
1           Dad           43            Male             188
2           Mom           42          Female             136
3           Sis           12          Female              83
4           Bro            8            Male              61
5           Dog            5          Female              44

In [49]:
str(myFamily)

'data.frame':	5 obs. of  4 variables:
 $ myFamilyNames  : Factor w/ 5 levels "Bro","Dad","Dog",..: 2 4 5 1 3
 $ myFamilyAges   : num  43 42 12 8 5
 $ myFamilyGenders: Factor w/ 2 levels "Female","Male": 2 1 1 2 1
 $ myFamilyWeights: num  188 136 83 61 44


In [50]:
class(myFamilyGenders)

[1] "character"

In [52]:
myFamilyStr <- data.frame(myFamilyNames, myFamilyAges, myFamilyGenders, myFamilyWeights, stringsAsFactors=FALSE)

In [54]:
str(myFamilyStr)

'data.frame':	5 obs. of  4 variables:
 $ myFamilyNames  : chr  "Dad" "Mom" "Sis" "Bro" ...
 $ myFamilyAges   : num  43 42 12 8 5
 $ myFamilyGenders: chr  "Male" "Female" "Female" "Male" ...
 $ myFamilyWeights: num  188 136 83 61 44


In [57]:
summary(myFamily)

 myFamilyNames  myFamilyAges myFamilyGenders myFamilyWeights
 Bro:1         Min.   : 5    Female:3        Min.   : 44.0  
 Dad:1         1st Qu.: 8    Male  :2        1st Qu.: 61.0  
 Dog:1         Median :12                    Median : 83.0  
 Mom:1         Mean   :22                    Mean   :102.4  
 Sis:1         3rd Qu.:42                    3rd Qu.:136.0  
               Max.   :43                    Max.   :188.0  

In [58]:
myFamily$myFamilyAges

[1] 43 42 12  8  5

In [59]:
myFamily[2,]

myFamilyNames myFamilyAges myFamilyGenders myFamilyWeights
2           Mom           42          Female             136

In [60]:
myFamilyAges <- c(myFamilyAges, 11)

In [61]:
myFamilyAges

[1] 43 42 12  8  5 11

In [62]:
myFamily$myFamilyAges

[1] 43 42 12  8  5

In [63]:
head(iris)

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
4          4.6         3.1          1.5         0.2  setosa
5          5.0         3.6          1.4         0.2  setosa
6          5.4         3.9          1.7         0.4  setosa

In [64]:
str(iris)

'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...


In [65]:
apply(iris[,1:4], 2, sum)

Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
       876.5        458.6        563.7        179.9

In [66]:
lapply(iris[,1:4], mean)

$Sepal.Length
[1] 5.843333

$Sepal.Width
[1] 3.057333

$Petal.Length
[1] 3.758

$Petal.Width
[1] 1.199333

In [2]:
sapply(iris[,1:4], mean) #vector or matrix

Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
    5.843333     3.057333     3.758000     1.199333

In [3]:
levels(iris$Species)

[1] "setosa"     "versicolor" "virginica"

In [5]:
tapply(iris$Sepal.Length, iris$Species, mean)

setosa versicolor  virginica 
     5.006      5.936      6.588

In [7]:
byspecies <- split(iris, iris$Species)

In [8]:
str(byspecies)

List of 3
 $ setosa    :'data.frame':	50 obs. of  5 variables:
  ..$ Sepal.Length: num [1:50] 5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
  ..$ Sepal.Width : num [1:50] 3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
  ..$ Petal.Length: num [1:50] 1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
  ..$ Petal.Width : num [1:50] 0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
  ..$ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ versicolor:'data.frame':	50 obs. of  5 variables:
  ..$ Sepal.Length: num [1:50] 7 6.4 6.9 5.5 6.5 5.7 6.3 4.9 6.6 5.2 ...
  ..$ Sepal.Width : num [1:50] 3.2 3.2 3.1 2.3 2.8 2.8 3.3 2.4 2.9 2.7 ...
  ..$ Petal.Length: num [1:50] 4.7 4.5 4.9 4 4.6 4.5 4.7 3.3 4.6 3.9 ...
  ..$ Petal.Width : num [1:50] 1.4 1.5 1.5 1.3 1.5 1.3 1.6 1 1.3 1.4 ...
  ..$ Species     : Factor w/ 3 levels "setosa","versicolor",..: 2 2 2 2 2 2 2 2 2 2 ...
 $ virginica :'data.frame':	50 obs. of  5 variables:
  ..$ Sepal.Length: num [1:50] 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3 6.

In [9]:
setosa <- subset(iris, Species="setosa")

In [10]:
head(setosa)

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
4          4.6         3.1          1.5         0.2  setosa
5          5.0         3.6          1.4         0.2  setosa
6          5.4         3.9          1.7         0.4  setosa

In [12]:
colsel <- subset(iris, select=c(Sepal.Length, Species))

In [13]:
head(colsel)

Sepal.Length Species
1          5.1  setosa
2          4.9  setosa
3          4.7  setosa
4          4.6  setosa
5          5.0  setosa
6          5.4  setosa

In [14]:
colsel <- subset(iris, select=-c(Sepal.Length, Species))

In [15]:
head(colsel)

Sepal.Width Petal.Length Petal.Width
1         3.5          1.4         0.2
2         3.0          1.4         0.2
3         3.2          1.3         0.2
4         3.1          1.5         0.2
5         3.6          1.4         0.2
6         3.9          1.7         0.4

In [16]:
x <- c(20,11,33,50,47)

In [17]:
sort(x)

[1] 11 20 33 47 50

In [19]:
order(x)

[1] 2 1 3 5 4

In [20]:
x[order(x)]

[1] 11 20 33 47 50

In [21]:
iris.ordered <- iris[order(iris$Sepal.Length), ]

In [23]:
head(iris.ordered)

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
14          4.3         3.0          1.1         0.1  setosa
9           4.4         2.9          1.4         0.2  setosa
39          4.4         3.0          1.3         0.2  setosa
43          4.4         3.2          1.3         0.2  setosa
42          4.5         2.3          1.3         0.3  setosa
4           4.6         3.1          1.5         0.2  setosa

In [24]:
head(iris[order(iris$Sepal.Length, iris$Petal.Length),])

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
14          4.3         3.0          1.1         0.1  setosa
39          4.4         3.0          1.3         0.2  setosa
43          4.4         3.2          1.3         0.2  setosa
9           4.4         2.9          1.4         0.2  setosa
42          4.5         2.3          1.3         0.3  setosa
23          4.6         3.6          1.0         0.2  setosa

In [25]:
sample(1:10,5)

[1] 9 4 8 5 6

In [26]:
sample(1:10, 5, replace=T)

[1] 10 10  9  1  5

In [27]:
aggregate(Sepal.Width~ Species, iris, mean)

Species Sepal.Width
1     setosa       3.428
2 versicolor       2.770
3  virginica       2.974

### 2) Bellman Equation 코드

In [3]:
x <- 1:4
y <- 1:3

In [4]:
rewards <- matrix(rep(0, 12), nrow=3)

In [5]:
rewards

[,1] [,2] [,3] [,4]
[1,]    0    0    0    0
[2,]    0    0    0    0
[3,]    0    0    0    0

In [6]:
rewards[2, 2] <- NA
rewards[1, 4] <- 1
rewards[2, 4] <- -1
rewards

[,1] [,2] [,3] [,4]
[1,]    0    0    0    1
[2,]    0   NA    0   -1
[3,]    0    0    0    0

In [7]:
values <- rewards # initial values

In [8]:
values
states <- expand.grid(x=x, y=y)
states

[,1] [,2] [,3] [,4]
[1,]    0    0    0    1
[2,]    0   NA    0   -1
[3,]    0    0    0    0

x y
1  1 1
2  2 1
3  3 1
4  4 1
5  1 2
6  2 2
7  3 2
8  4 2
9  1 3
10 2 3
11 3 3
12 4 3

In [9]:
# Transition probability
transition <- list("N" = c("N" = 0.8, "S" = 0, "E" = 0.1, "W" = 0.1), 
                   "S"= c("S" = 0.8, "N" = 0, "E" = 0.1, "W" = 0.1),
                   "E"= c("E" = 0.8, "W" = 0, "S" = 0.1, "N" = 0.1),
                   "W"= c("W" = 0.8, "E" = 0, "S" = 0.1, "N" = 0.1))

In [10]:
transition

$N
  N   S   E   W 
0.8 0.0 0.1 0.1 

$S
  S   N   E   W 
0.8 0.0 0.1 0.1 

$E
  E   W   S   N 
0.8 0.0 0.1 0.1 

$W
  W   E   S   N 
0.8 0.0 0.1 0.1

In [11]:
# The value of an action (e.g. move north means y + 1)
action.values <- list("N" = c("x" = 0, "y" = 1), 
                      "S" = c("x" = 0, "y" = -1),
                      "E" = c("x" = -1, "y" = 0),
                      "W" = c("x" = 1, "y" = 0))

In [12]:
action.values

$N
x y 
0 1 

$S
 x  y 
 0 -1 

$E
 x  y 
-1  0 

$W
x y 
1 0

In [13]:
# act() function serves to move the robot through states based on an action
act <- function(action, state) {
  action.value <- action.values[[action]]
  new.state <- state
  #
  if(state["x"] == 4 && state["y"] == 1 || (state["x"] == 4 && state["y"] == 2))
    return(state)
  #
  new.x = state["x"] + action.value["x"]
  new.y = state["y"] + action.value["y"]
  # Constrained by edge of grid
  new.state["x"] <- min(x[length(x)], max(x[1], new.x))
  new.state["y"] <- min(y[length(y)], max(y[1], new.y))
  #
  if(is.na(rewards[new.state["y"], new.state["x"]]))
    new.state <- state
  #
  return(new.state)
}

In [14]:
bellman.update <- function(action, state, values, gamma=1) {
  state.transition.prob <- transition[[action]]
  q <- rep(0, length(state.transition.prob))
  for(i in 1:length(state.transition.prob)) {        
    new.state <- act(names(state.transition.prob)[i], state) 
    q[i] <- (state.transition.prob[i] * (rewards[state["y"], state["x"]] + (gamma * values[new.state["y"], new.state["x"]])))
  }
  sum(q)
}

In [15]:
value.iteration <- function(states, actions, rewards, values, gamma, niter) {
  for (j in 1:niter) {
    for (i in 1:nrow(states)) {
      state <- unlist(states[i,])
      if(i %in% c(4, 8)) next # terminal states
      q.values <- as.numeric(lapply(actions, bellman.update, state=state, values=values, gamma=gamma))
      values[state["y"], state["x"]] <- max(q.values)
    }
  }
  return(values)
}

In [16]:
final.values <- value.iteration(states=states, actions=actions, rewards=rewards, values=values, gamma=0.99, niter=100)

In [17]:
final.values

[,1]      [,2]      [,3]     [,4]
[1,] 0.9516605 0.9651596 0.9773460  1.00000
[2,] 0.9397944        NA 0.8948359 -1.00000
[3,] 0.9266500 0.9150957 0.9027132  0.81989